version: "3"
networks:
  study:
services:
  service:
    container_name: "openapi-service"
    build:
      context: ./service
    ports:
    - "8080:8080"
    - "9990:9990"
    - "8787:8787"
    - "4848:4848"
    networks:
      - study
  client:
    container_name: "openapi-client"
    build:
      context: ./client
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8788:8787"
      - "4849:4848"
    networks:
      - study